export const yelp_sample_response_2 = [

{
  "address": "\"2528 S Figueroa St\",\"Los Angeles, CA 90007\"",
  "item_id": "dirt-dog-los-angeles-4",
  "city": "Los Angeles",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/K8HGdtvSCxAxQYLg65e3Vw/o.jpg",
  "latitude": 34.0282923762355,
  "rating": 4.5,
  "review_count": 819,
  "url": "https://www.yelp.com/biz/dirt-dog-los-angeles-4?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+12137491813",
  "price": 1,
  "name": "Dirt Dog",
  "state": "CA",
  "categories": ["Hot Dogs"],
  "longitude": -118.275208244705
},
{
  "address": "\"1451 Dana St\",\"Los Angeles, CA 90007\"",
  "item_id": "ignatius-cafe-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/5UtRc3a4n-ATdVhlfCCA-Q/o.jpg",
  "latitude": 34.031914,
  "rating": 4.5,
  "review_count": 189,
  "url": "https://www.yelp.com/biz/ignatius-cafe-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "",
  "price": 1,
  "name": "Ignatius Cafe",
  "state": "CA",
  "categories": [
    "Cafes",
    "Coffee & Tea"
  ],
  "longitude": -118.293154
},
{
  "address": "\"1101 W 23rd St\",\"Los Angeles, CA 90007\"",
  "item_id": "everytable-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/K7EKgPIqAPNCkyDR7QDP0w/o.jpg",
  "latitude": 34.0350349992514,
  "rating": 4.5,
  "review_count": 186,
  "url": "https://www.yelp.com/biz/everytable-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+12139735095",
  "price": 1,
  "name": "Everytable",
  "state": "CA",
  "categories": [
    "Fast Food",
    "Vietnamese",
    "Salad"
  ],
  "longitude": -118.283531293273
},
{
  "address": "\"1933 S Broadway\",\"Lobby\",\"Los Angeles, CA 90007\"",
  "item_id": "coffee-by-kofi-los-angeles-2",
  "city": "Los Angeles",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/r7bfUA1uscmONBaE8A5BJQ/o.jpg",
  "latitude": 34.0312448,
  "rating": 5,
  "review_count": 54,
  "url": "https://www.yelp.com/biz/coffee-by-kofi-los-angeles-2?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+16467259580",
  "price": 1,
  "name": "Coffee by KOFI",
  "state": "CA",
  "categories": ["Coffee & Tea"],
  "longitude": -118.2665321
},
{
  "address": "\"1436 W Jefferson Blvd\",\"Ste 70\",\"Los Angeles, CA 90007\"",
  "item_id": "revolutionario-north-african-tacos-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/veDTMpjLuEClBqXMxJFw-g/o.jpg",
  "latitude": 34.02523,
  "rating": 4.5,
  "review_count": 376,
  "url": "https://www.yelp.com/biz/revolutionario-north-african-tacos-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+14242233526",
  "price": 1,
  "name": "Revolutionario: North African Tacos",
  "state": "CA",
  "categories": [
    "Mexican",
    "Halal",
    "African"
  ],
  "longitude": -118.29857
},
{
  "address": "\"3655 S Grand Ave\",\"Ste C9\",\"Los Angeles, CA 90007\"",
  "item_id": "holbox-los-angeles-2",
  "city": "Los Angeles",
  "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/Uq7AhrhJrAg3CCdX1KLDHw/o.jpg",
  "latitude": 34.0171789745852,
  "rating": 5,
  "review_count": 93,
  "url": "https://www.yelp.com/biz/holbox-los-angeles-2?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+12139869972",
  "price": 2,
  "name": "Holbox",
  "state": "CA",
  "categories": [
    "Mexican",
    "Latin American",
    "Seafood"
  ],
  "longitude": -118.278350606561
},
{
  "address": "\"3655 S Grand Ave\",\"Ste C2\",\"Los Angeles, CA 90007\"",
  "item_id": "azla-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/mY97gY2G8Yblo0UzvaPvxA/o.jpg",
  "latitude": 34.0173639,
  "rating": 4.5,
  "review_count": 258,
  "url": "https://www.yelp.com/biz/azla-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+12137457455",
  "price": 1,
  "name": "Azla",
  "state": "CA",
  "categories": [
    "Gluten-Free",
    "Ethiopian",
    "Vegan"
  ],
  "longitude": -118.278314392065
},
{
  "address": "\"3655 S Grand Ave\",\"Ste C6\",\"Los Angeles, CA 90007\"",
  "item_id": "chichen-itza-restaurant-los-angeles-3",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/3ch4AcGy7sl_aybqhgRFOA/o.jpg",
  "latitude": 34.01744,
  "rating": 4.5,
  "review_count": 967,
  "url": "https://www.yelp.com/biz/chichen-itza-restaurant-los-angeles-3?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+12137411075",
  "price": 2,
  "name": "Chichen Itza Restaurant",
  "state": "CA",
  "categories": ["Mexican"],
  "longitude": -118.2783
},
{
  "address": "\"2800 S Grand Ave\",\"Los Angeles, CA 90007\"",
  "item_id": "serees-coffee-shop-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/zDr4ZsQa3IcP5UeXTZW8KA/o.jpg",
  "latitude": 34.02444,
  "rating": 4.5,
  "review_count": 66,
  "url": "https://www.yelp.com/biz/serees-coffee-shop-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+12137478233",
  "price": 1,
  "name": "Seree's Coffee Shop",
  "state": "CA",
  "categories": [
    "Breakfast & Brunch",
    "Chinese",
    "Japanese"
  ],
  "longitude": -118.27315
},
{
  "address": "\"1933 S Broadway\",\"Los Angeles, CA 90007\"",
  "item_id": "eat-show-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/fUadL71FK8_OpTWHSN3Vng/o.jpg",
  "latitude": 34.030803,
  "rating": 4.5,
  "review_count": 86,
  "url": "https://www.yelp.com/biz/eat-show-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+16262808588",
  "price": 0,
  "name": "EAT Show",
  "state": "CA",
  "categories": ["Local Flavor"],
  "longitude": -118.266853
},
{
  "address": "\"817 W 34th St\",\"USC Office of Religious Life\",\"Los Angeles, CA 90089\"",
  "item_id": "the-good-karma-cafe-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/dmBS3yQYU-j_cIvGQuXgcA/o.jpg",
  "latitude": 34.02324,
  "rating": 4.5,
  "review_count": 43,
  "url": "https://www.yelp.com/biz/the-good-karma-cafe-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90089",
  "phone": "+12133733606",
  "price": 1,
  "name": "The Good Karma Cafe",
  "state": "CA",
  "categories": [
    "Italian",
    "Mexican",
    "Vegan"
  ],
  "longitude": -118.28417
},
{
  "address": "\"3850 S Figueroa St\",\"Los Angeles, CA 90037\"",
  "item_id": "figueroa-philly-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/fIdgkh6oTLdd5XSslFgtlw/o.jpg",
  "latitude": 34.014196,
  "rating": 4.5,
  "review_count": 847,
  "url": "https://www.yelp.com/biz/figueroa-philly-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90037",
  "phone": "+12137489073",
  "price": 1,
  "name": "Figueroa Philly",
  "state": "CA",
  "categories": [
    "Cheesesteaks",
    "American (Traditional)",
    "Sandwiches"
  ],
  "longitude": -118.282417
},
{
  "address": "\"2316 S Union Ave\",\"Los Angeles, CA 90007\"",
  "item_id": "natures-brew-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/DG1Ug0iUdepGPKzdiGrvzg/o.jpg",
  "latitude": 34.0342569,
  "rating": 4,
  "review_count": 461,
  "url": "https://www.yelp.com/biz/natures-brew-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+12137419393",
  "price": 1,
  "name": "Nature's Brew",
  "state": "CA",
  "categories": [
    "Breakfast & Brunch",
    "Sandwiches",
    "Coffee & Tea"
  ],
  "longitude": -118.283559
},
{
  "address": "\"1277 W Jefferson Blvd\",\"Los Angeles, CA 90007\"",
  "item_id": "himalayan-house-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/gEcjD8fG5PO012hv_sfMeA/o.jpg",
  "latitude": 34.0256379,
  "rating": 4.5,
  "review_count": 191,
  "url": "https://www.yelp.com/biz/himalayan-house-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+13237669775",
  "price": 2,
  "name": "Himalayan House",
  "state": "CA",
  "categories": [
    "Himalayan/Nepalese",
    "Indian"
  ],
  "longitude": -118.2940196
},
{
  "address": "\"2703 S Vermont Ave\",\"Los Angeles, CA 90007\"",
  "item_id": "monarca-pasta-and-grill-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/EFwfO2YF9jfAdcC1pltDxg/o.jpg",
  "latitude": 34.0302958095499,
  "rating": 4.5,
  "review_count": 100,
  "url": "https://www.yelp.com/biz/monarca-pasta-and-grill-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+13237318149",
  "price": 1,
  "name": "Monarca Pasta & Grill",
  "state": "CA",
  "categories": ["Italian"],
  "longitude": -118.292084693909
},
{
  "address": "\"Los Angeles, CA 90007\"",
  "item_id": "amazebowls-los-angeles-2",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/rcV-okggh1y_5TV5_cr_1w/o.jpg",
  "latitude": 34.02911,
  "rating": 4.5,
  "review_count": 151,
  "url": "https://www.yelp.com/biz/amazebowls-los-angeles-2?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+13103842202",
  "price": 1,
  "name": "Amazebowls",
  "state": "CA",
  "categories": [
    "Gluten-Free",
    "Food Trucks",
    "Vegan"
  ],
  "longitude": -118.28306
},
{
  "address": "\"3584 S Figueroa St\",\"Los Angeles, CA 90007\"",
  "item_id": "pizza-studio-los-angeles-5",
  "city": "Los Angeles",
  "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/L-d2mBtasuqfpqDFKZpoFA/o.jpg",
  "latitude": 34.018666,
  "rating": 4,
  "review_count": 443,
  "url": "https://www.yelp.com/biz/pizza-studio-los-angeles-5?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+12137636124",
  "price": 1,
  "name": "Pizza Studio",
  "state": "CA",
  "categories": [
    "Pizza",
    "Salad"
  ],
  "longitude": -118.281577
},
{
  "address": "\"2308 S Union Ave\",\"Los Angeles, CA 90007\"",
  "item_id": "bacaro-la-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/gg0P3dCC7EGX_lxFfdrcVg/o.jpg",
  "latitude": 34.0344772338867,
  "rating": 4,
  "review_count": 1191,
  "url": "https://www.yelp.com/biz/bacaro-la-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+12137487205",
  "price": 2,
  "name": "Bacaro LA",
  "state": "CA",
  "categories": [
    "American (New)",
    "Wine Bars",
    "Breakfast & Brunch"
  ],
  "longitude": -118.283416748047
},
{
  "address": "\"3470 McClintock Ave\",\"USC's Main Campus\",\"Los Angeles, CA 90089\"",
  "item_id": "armandos-lunch-truck-los-angeles-3",
  "city": "Los Angeles",
  "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/5U2WVa7ZfXjMML9mYD_19Q/o.jpg",
  "latitude": 34.02526361973,
  "rating": 4.5,
  "review_count": 117,
  "url": "https://www.yelp.com/biz/armandos-lunch-truck-los-angeles-3?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90089",
  "phone": "+15626502951",
  "price": 1,
  "name": "Armando's Lunch Truck",
  "state": "CA",
  "categories": [
    "Mexican",
    "Food Trucks"
  ],
  "longitude": -118.28776314109
},
{
  "address": "\"4069 S Avalon Blvd\",\"Los Angeles, CA 90011\"",
  "item_id": "tire-shop-taqueria-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/Nc64qDdWngn5hwS7nLdK4g/o.jpg",
  "latitude": 34.0097381464074,
  "rating": 5,
  "review_count": 213,
  "url": "https://www.yelp.com/biz/tire-shop-taqueria-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90011",
  "phone": "",
  "price": 1,
  "name": "Tire Shop Taqueria",
  "state": "CA",
  "categories": ["Mexican"],
  "longitude": -118.265285901725
},
{
  "address": "\"231 Venice Blvd\",\"Los Angeles, CA 90015\"",
  "item_id": "right-away-231-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/wijrvGH7PFE4A_JHpjoJnw/o.jpg",
  "latitude": 34.03554,
  "rating": 5,
  "review_count": 39,
  "url": "https://www.yelp.com/biz/right-away-231-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90015",
  "phone": "+12135365517",
  "price": 1,
  "name": "Right Away 231",
  "state": "CA",
  "categories": [
    "Italian",
    "Mexican",
    "American (Traditional)"
  ],
  "longitude": -118.26546
},
{
  "address": "\"1479 W Adams Blvd\",\"Los Angeles, CA 90007\"",
  "item_id": "jesses-camarones-restaurant-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/U5NT_02WcBkOKgok4eRUgw/o.jpg",
  "latitude": 34.0328949,
  "rating": 4.5,
  "review_count": 102,
  "url": "https://www.yelp.com/biz/jesses-camarones-restaurant-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+13237356399",
  "price": 1,
  "name": "Jesse's Camarones Restaurant",
  "state": "CA",
  "categories": ["Seafood"],
  "longitude": -118.2938062
},
{
  "address": "\"2498 S Figueroa St\",\"Los Angeles, CA 90007\"",
  "item_id": "jacks-n-joe-los-angeles-6",
  "city": "Los Angeles",
  "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/JJUNh7mdytVyeZ_Uyt2L7w/o.jpg",
  "latitude": 34.02876,
  "rating": 4,
  "review_count": 1643,
  "url": "https://www.yelp.com/biz/jacks-n-joe-los-angeles-6?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+12137484565",
  "price": 2,
  "name": "Jacks N Joe",
  "state": "CA",
  "categories": ["Breakfast & Brunch"],
  "longitude": -118.27517
},
{
  "address": "\"1150 S Hope St\",\"Los Angeles, CA 90015\"",
  "item_id": "aladdins-coffee-shop-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/UtiuP1lisMRAVMPStnbmHw/o.jpg",
  "latitude": 34.04081,
  "rating": 4.5,
  "review_count": 111,
  "url": "https://www.yelp.com/biz/aladdins-coffee-shop-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90015",
  "phone": "",
  "price": 1,
  "name": "Aladdin's Coffee Shop",
  "state": "CA",
  "categories": [
    "Caterers",
    "Latin American"
  ],
  "longitude": -118.2639
},
{
  "address": "\"2106 S Olive St\",\"Los Angeles, CA 90007\"",
  "item_id": "food-haus-café-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/kZfrS5RTq3_I7K91qtuFHA/o.jpg",
  "latitude": 34.02991,
  "rating": 4,
  "review_count": 941,
  "url": "https://www.yelp.com/biz/food-haus-caf%C3%A9-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+12137410007",
  "price": 2,
  "name": "Food Haus Café",
  "state": "CA",
  "categories": [
    "Soul Food",
    "Breakfast & Brunch",
    "Cafes"
  ],
  "longitude": -118.26869
},
{
  "address": "\"1969 S Vermont Ave\",\"Los Angeles, CA 90007\"",
  "item_id": "with-love-market-and-cafe-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/mI-5YLN1pumBskeKbsibYg/o.jpg",
  "latitude": 34.0384925109839,
  "rating": 5,
  "review_count": 161,
  "url": "https://www.yelp.com/biz/with-love-market-and-cafe-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+12138177294",
  "price": 1,
  "name": "With Love Market & Cafe",
  "state": "CA",
  "categories": [
    "Grocery",
    "Sandwiches",
    "Coffee & Tea"
  ],
  "longitude": -118.291610594329
},
{
  "address": "\"2321 S Hoover St\",\"Los Angeles, CA 90007\"",
  "item_id": "cafe-amandine-los-angeles-3",
  "city": "Los Angeles",
  "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/4wQeSc3nkMRBo3OopJBjFQ/o.jpg",
  "latitude": 34.0346442,
  "rating": 5,
  "review_count": 21,
  "url": "https://www.yelp.com/biz/cafe-amandine-los-angeles-3?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+12135365094",
  "price": 1,
  "name": "Cafe Amandine",
  "state": "CA",
  "categories": [
    "Breakfast & Brunch",
    "Sandwiches",
    "Coffee & Tea"
  ],
  "longitude": -118.2841619
},
{
  "address": "\"1243 S Alvarado St\",\"Ste B-1\",\"Los Angeles, CA 90006\"",
  "item_id": "coffee-gram-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/pfU9wyVGIJa0O2cGrq0EEg/o.jpg",
  "latitude": 34.0477222212369,
  "rating": 4.5,
  "review_count": 56,
  "url": "https://www.yelp.com/biz/coffee-gram-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90006",
  "phone": "+12139086767",
  "price": 1,
  "name": "Coffee Gram",
  "state": "CA",
  "categories": [
    "Delis",
    "Juice Bars & Smoothies",
    "Coffee & Tea"
  ],
  "longitude": -118.282971382141
},
{
  "address": "\"2403 S Vermont Ave\",\"Los Angeles, CA 90007\"",
  "item_id": "birds-nest-cafe-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/dK9JeyRNejq7hKBTtc_wuw/o.jpg",
  "latitude": 34.0344334,
  "rating": 4,
  "review_count": 253,
  "url": "https://www.yelp.com/biz/birds-nest-cafe-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+13236417986",
  "price": 2,
  "name": "Bird's Nest Cafe",
  "state": "CA",
  "categories": [
    "Breakfast & Brunch",
    "Cafes",
    "Sandwiches"
  ],
  "longitude": -118.2916849
},
{
  "address": "\"2280 S Figueroa St\",\"Los Angeles, CA 90007\"",
  "item_id": "the-rustiq-table-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/Ycw_xfWKv-8Oo8ZURyZKJw/o.jpg",
  "latitude": 34.0308825,
  "rating": 4,
  "review_count": 107,
  "url": "https://www.yelp.com/biz/the-rustiq-table-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+12135365542",
  "price": 2,
  "name": "The Rustiq Table",
  "state": "CA",
  "categories": [
    "Comfort Food",
    "Breakfast & Brunch",
    "Coffee & Tea"
  ],
  "longitude": -118.2741112
},
{
  "address": "\"Los Angeles, CA 90007\"",
  "item_id": "urban-espresso-los-angeles-6",
  "city": "Los Angeles",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/6uA0aQr1dQk2P92IBgwfqw/o.jpg",
  "latitude": 34.02911,
  "rating": 4.5,
  "review_count": 22,
  "url": "https://www.yelp.com/biz/urban-espresso-los-angeles-6?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+15627946484",
  "price": 1,
  "name": "Urban Espresso",
  "state": "CA",
  "categories": [
    "Breakfast & Brunch",
    "Food Trucks",
    "Coffee & Tea"
  ],
  "longitude": -118.28306
},
{
  "address": "\"3655 S Grand Ave\",\"Ste 240\",\"Los Angeles, CA 90007\"",
  "item_id": "mercado-la-paloma-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/Sg8Oo4PPUWMFDPs6CoH7RA/o.jpg",
  "latitude": 34.01744,
  "rating": 4.5,
  "review_count": 128,
  "url": "https://www.yelp.com/biz/mercado-la-paloma-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+12137481963",
  "price": 1,
  "name": "Mercado La Paloma",
  "state": "CA",
  "categories": [
    "Mexican",
    "Latin American",
    "Breakfast & Brunch"
  ],
  "longitude": -118.2783
},
{
  "address": "\"2215 S Vermont Ave\",\"Los Angeles, CA 90007\"",
  "item_id": "caveman-kitchen-los-angeles-2",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/oXxxoijmvQBZUka-t4LwVg/o.jpg",
  "latitude": 34.0358848571777,
  "rating": 4,
  "review_count": 295,
  "url": "https://www.yelp.com/biz/caveman-kitchen-los-angeles-2?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+13237373717",
  "price": 1,
  "name": "Caveman Kitchen",
  "state": "CA",
  "categories": [
    "Latin American",
    "Burgers"
  ],
  "longitude": -118.291900634766
},
{
  "address": "\"3764 S Normandie Ave\",\"Los Angeles, CA 90007\"",
  "item_id": "hamburger-dans-4-los-angeles-2",
  "city": "Los Angeles",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/EXjFe8XoPaQrY8qakTsQLw/o.jpg",
  "latitude": 34.0184296,
  "rating": 4.5,
  "review_count": 110,
  "url": "https://www.yelp.com/biz/hamburger-dans-4-los-angeles-2?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+13237371522",
  "price": 1,
  "name": "Hamburger Dan's 4",
  "state": "CA",
  "categories": [
    "Mexican",
    "Breakfast & Brunch",
    "Burgers"
  ],
  "longitude": -118.3000302
},
{
  "address": "\"924 W Washington Blvd\",\"Los Angeles, CA 90015\"",
  "item_id": "el-ostion-taco-truck-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/5sOI5Wt8umnnenAZH20G2g/o.jpg",
  "latitude": 34.0370227,
  "rating": 4.5,
  "review_count": 38,
  "url": "https://www.yelp.com/biz/el-ostion-taco-truck-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90015",
  "phone": "+12137491147",
  "price": 1,
  "name": "El Ostion Taco Truck",
  "state": "CA",
  "categories": [
    "Mexican",
    "Food Trucks"
  ],
  "longitude": -118.2782302
},
{
  "address": "\"2516 S Figueroa St\",\"Los Angeles, CA 90007\"",
  "item_id": "poke-by-hawaii-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/DjhwRkxKF0yf_mJ83UqjXQ/o.jpg",
  "latitude": 34.0284441411495,
  "rating": 4,
  "review_count": 124,
  "url": "https://www.yelp.com/biz/poke-by-hawaii-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+12139449889",
  "price": 2,
  "name": "Poke By Hawaii",
  "state": "CA",
  "categories": [
    "Hawaiian",
    "Poke"
  ],
  "longitude": -118.275777697563
},
{
  "address": "\"2719 S Vermont Ave\",\"Los Angeles, CA 90007\"",
  "item_id": "la-valentina-mexican-grill-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/KnRqtMyWwGogBHSn4kqFVQ/o.jpg",
  "latitude": 34.0300018,
  "rating": 4,
  "review_count": 175,
  "url": "https://www.yelp.com/biz/la-valentina-mexican-grill-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+13237344071",
  "price": 1,
  "name": "La Valentina Mexican Grill",
  "state": "CA",
  "categories": ["Mexican"],
  "longitude": -118.2916849
},
{
  "address": "\"2274 W Pico Blvd\",\"Los Angeles, CA 90006\"",
  "item_id": "el-grullense-los-angeles-3",
  "city": "Los Angeles",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/3pk_kf3sa61hgmCGQgfe9Q/o.jpg",
  "latitude": 34.047,
  "rating": 4.5,
  "review_count": 73,
  "url": "https://www.yelp.com/biz/el-grullense-los-angeles-3?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90006",
  "phone": "+12134879540",
  "price": 1,
  "name": "El Grullense",
  "state": "CA",
  "categories": ["Mexican"],
  "longitude": -118.28618
},
{
  "address": "\"3758 S Figueroa St\",\"Los Angeles, CA 90007\"",
  "item_id": "chick-fil-a-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/pET753W1TafL-tv9OYwh3Q/o.jpg",
  "latitude": 34.0163034,
  "rating": 4,
  "review_count": 305,
  "url": "https://www.yelp.com/biz/chick-fil-a-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+12137478721",
  "price": 1,
  "name": "Chick-fil-A",
  "state": "CA",
  "categories": ["Fast Food"],
  "longitude": -118.2826251
},
{
  "address": "\"3335 S Figueroa St\",\"Los Angeles, CA 90007\"",
  "item_id": "cream-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/cZcQES731RZuQd7zXDbtbQ/o.jpg",
  "latitude": 34.0232620499708,
  "rating": 4,
  "review_count": 237,
  "url": "https://www.yelp.com/biz/cream-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+12137429090",
  "price": 1,
  "name": "CREAM",
  "state": "CA",
  "categories": [
    "Ice Cream & Frozen Yogurt",
    "Tacos",
    "Desserts"
  ],
  "longitude": -118.279513928173
},
{
  "address": "\"1515 Maple Ave\",\"Ste 1\",\"Los Angeles, CA 90015\"",
  "item_id": "yang-ban-sul-lung-tang-restaurant-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/22lIpyvR-kci66vPMPXjlg/o.jpg",
  "latitude": 34.03235,
  "rating": 4.5,
  "review_count": 139,
  "url": "https://www.yelp.com/biz/yang-ban-sul-lung-tang-restaurant-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90015",
  "phone": "+12134894640",
  "price": 1,
  "name": "Yang Ban Sul Lung Tang Restaurant",
  "state": "CA",
  "categories": ["Korean"],
  "longitude": -118.25946
},
{
  "address": "\"2524 Maple Ave\",\"Los Angeles, CA 90011\"",
  "item_id": "birrieria-los-gonzalez-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/TcqY34vjYm6_LDUT1EUUAg/o.jpg",
  "latitude": 34.0236206054688,
  "rating": 4.5,
  "review_count": 38,
  "url": "https://www.yelp.com/biz/birrieria-los-gonzalez-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90011",
  "phone": "+13232168795",
  "price": 1,
  "name": "Birrieria Los Gonzalez",
  "state": "CA",
  "categories": ["Mexican"],
  "longitude": -118.265083312988
},
{
  "address": "\"1733 W Adams Blvd\",\"Los Angeles, CA 90018\"",
  "item_id": "la-estrella-mexican-food-los-angeles-2",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/lynn2ABwwc7REEYl_21Jcg/o.jpg",
  "latitude": 34.033053,
  "rating": 4.5,
  "review_count": 62,
  "url": "https://www.yelp.com/biz/la-estrella-mexican-food-los-angeles-2?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90018",
  "phone": "+13235331229",
  "price": 1,
  "name": "La Estrella Mexican Food",
  "state": "CA",
  "categories": [
    "Mexican",
    "Food Trucks"
  ],
  "longitude": -118.301235
},
{
  "address": "\"421 Venice Blvd\",\"Los Angeles, CA 90015\"",
  "item_id": "el-patroncito-mexican-cuisine-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/etG_lmtI_TlIZl5wMsp3zg/o.jpg",
  "latitude": 34.036967788469,
  "rating": 4.5,
  "review_count": 58,
  "url": "https://www.yelp.com/biz/el-patroncito-mexican-cuisine-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90015",
  "phone": "+12137459500",
  "price": 2,
  "name": "El Patroncito Mexican Cuisine",
  "state": "CA",
  "categories": ["Mexican"],
  "longitude": -118.2682534625
},
{
  "address": "\"1309 S Hoover St\",\"Los Angeles, CA 90006\"",
  "item_id": "happy-taco-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/uxw_uKgSGeRhzm5z5zpguw/o.jpg",
  "latitude": 34.0469713238291,
  "rating": 4.5,
  "review_count": 212,
  "url": "https://www.yelp.com/biz/happy-taco-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90006",
  "phone": "+12133841309",
  "price": 1,
  "name": "Happy Taco",
  "state": "CA",
  "categories": [
    "Mexican",
    "American (Traditional)"
  ],
  "longitude": -118.284385576844
},
{
  "address": "\"936 W 23rd St\",\"Los Angeles, CA 90007\"",
  "item_id": "23rd-street-cafe-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/KdVnOp7ZvZlv8Yo-ujNA5w/o.jpg",
  "latitude": 34.0339369301652,
  "rating": 4,
  "review_count": 307,
  "url": "https://www.yelp.com/biz/23rd-street-cafe-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+12137491593",
  "price": 1,
  "name": "23rd Street Cafe",
  "state": "CA",
  "categories": [
    "American (New)",
    "Mexican",
    "Indian"
  ],
  "longitude": -118.280889987946
},
{
  "address": "\"2700 S Figueroa St\",\"Los Angeles, CA 90007\"",
  "item_id": "leno-juice-bar-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/OXBlpgEySZH5819BkdL9Xg/o.jpg",
  "latitude": 34.0271529,
  "rating": 4,
  "review_count": 148,
  "url": "https://www.yelp.com/biz/leno-juice-bar-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+12137465366",
  "price": 2,
  "name": "LENO Juice Bar",
  "state": "CA",
  "categories": [
    "Acai Bowls",
    "Breakfast & Brunch",
    "Juice Bars & Smoothies"
  ],
  "longitude": -118.2764725
},
{
  "address": "\"3742 S Figueroa St\",\"Los Angeles, CA 90007\"",
  "item_id": "california-gogi-grill-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/BaPDbMXnt078A6YCeZHN6w/o.jpg",
  "latitude": 34.017343,
  "rating": 4,
  "review_count": 285,
  "url": "https://www.yelp.com/biz/california-gogi-grill-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+12137441910",
  "price": 1,
  "name": "California Gogi Grill",
  "state": "CA",
  "categories": ["Korean"],
  "longitude": -118.2828057
},
{
  "address": "\"3009 S Figueroa St\",\"Los Angeles, CA 90007\"",
  "item_id": "la-taquiza-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/J6X0q19wGqFv_UwrlNI95Q/o.jpg",
  "latitude": 34.0249016337977,
  "rating": 4,
  "review_count": 567,
  "url": "https://www.yelp.com/biz/la-taquiza-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+12137419795",
  "price": 1,
  "name": "La Taquiza",
  "state": "CA",
  "categories": [
    "Mexican",
    "Breakfast & Brunch",
    "Salad"
  ],
  "longitude": -118.278697446791
},
{
  "address": "\"2314 S Union Ave\",\"Los Angeles, CA 90007\"",
  "item_id": "ebaes-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/INi5drOCfhTTuAPg43dfag/o.jpg",
  "latitude": 34.0344536304474,
  "rating": 4,
  "review_count": 499,
  "url": "https://www.yelp.com/biz/ebaes-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90007",
  "phone": "+12137476888",
  "price": 2,
  "name": "Ebaes",
  "state": "CA",
  "categories": [
    "Tapas/Small Plates",
    "Ramen",
    "Sushi Bars"
  ],
  "longitude": -118.283669427037
},

]
