export const yelp_sample_response_1 = [

{
  "address": "\"6208 W 87th St\",\"Los Angeles, CA 90045\"",
  "item_id": "the-candy-bar-hookah-shoppe-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/rIxCdJMlWwcaoh9Zk-OQ5g/o.jpg",
  "latitude": 33.9584346,
  "rating": 5,
  "review_count": 88,
  "url": "https://www.yelp.com/biz/the-candy-bar-hookah-shoppe-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13106700708",
  "price": 2,
  "name": "The Candy Bar Hookah Shoppe",
  "state": "CA",
  "categories": [
    "Head Shops",
    "Hookah Bars",
    "Vape Shops"
  ],
  "longitude": -118.3939655
},
{
  "address": "\"8939 S Sepulveda Blvd\",\"Ste 107\",\"Los Angeles, CA 90045\"",
  "item_id": "courtyard-cafe-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/ODAzkdLnxmbAfcPhnq0O-g/o.jpg",
  "latitude": 33.95486,
  "rating": 4.5,
  "review_count": 138,
  "url": "https://www.yelp.com/biz/courtyard-cafe-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13104100770",
  "price": 1,
  "name": "Courtyard Cafe",
  "state": "CA",
  "categories": [
    "Breakfast & Brunch",
    "Cafes"
  ],
  "longitude": -118.39672
},
{
  "address": "\"6220 W 87th St\",\"Los Angeles, CA 90045\"",
  "item_id": "the-ramen-joint-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/rbFK820odlWwJxWJL9SYaA/o.jpg",
  "latitude": 33.9584404,
  "rating": 4.5,
  "review_count": 529,
  "url": "https://www.yelp.com/biz/the-ramen-joint-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+14242279328",
  "price": 2,
  "name": "The Ramen Joint",
  "state": "CA",
  "categories": ["Ramen"],
  "longitude": -118.3941214
},
{
  "address": "\"6231 W 87th St\",\"Los Angeles, CA 90045\"",
  "item_id": "olive-it-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/XNw-g6SN6nxLzhS0ngK89A/o.jpg",
  "latitude": 33.9587096,
  "rating": 4.5,
  "review_count": 175,
  "url": "https://www.yelp.com/biz/olive-it-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13102422092",
  "price": 1,
  "name": "Olive It",
  "state": "CA",
  "categories": [
    "Delis",
    "Sandwiches",
    "Salad"
  ],
  "longitude": -118.394182
},
{
  "address": "\"9149 S Sepulveda Blvd\",\"Los Angeles, CA 90045\"",
  "item_id": "in-n-out-burger-los-angeles-2",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/dpvfWa0xScsyo4ZMRc-XZw/o.jpg",
  "latitude": 33.9537021005473,
  "rating": 4,
  "review_count": 1199,
  "url": "https://www.yelp.com/biz/in-n-out-burger-los-angeles-2?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+18007861000",
  "price": 1,
  "name": "In-N-Out Burger",
  "state": "CA",
  "categories": [
    "Burgers",
    "Fast Food"
  ],
  "longitude": -118.396771789024
},
{
  "address": "\"1120 W Florence Ave\",\"Unit C\",\"Inglewood, CA 90301\"",
  "item_id": "equelecuá-cuban-cafe-inglewood-2",
  "city": "Inglewood",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/pFLLUZgXV-MEVVqACPxhvg/o.jpg",
  "latitude": 33.9608934,
  "rating": 4.5,
  "review_count": 405,
  "url": "https://www.yelp.com/biz/equelecu%C3%A1-cuban-cafe-inglewood-2?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90301",
  "phone": "+13237412822",
  "price": 2,
  "name": "Equelecuá Cuban Cafe",
  "state": "CA",
  "categories": [
    "Vegetarian",
    "Cuban",
    "Vegan"
  ],
  "longitude": -118.3761448
},
{
  "address": "\"5862 Arbor Vitae St\",\"Los Angeles, CA 90045\"",
  "item_id": "alikis-greek-taverna-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/0FXM1E1Cuu5cie_tazfobg/o.jpg",
  "latitude": 33.9524703946447,
  "rating": 4.5,
  "review_count": 723,
  "url": "https://www.yelp.com/biz/alikis-greek-taverna-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13106459555",
  "price": 2,
  "name": "Aliki's Greek Taverna",
  "state": "CA",
  "categories": [
    "Mediterranean",
    "Greek"
  ],
  "longitude": -118.385242001852
},
{
  "address": "\"1117 W Manchester Blvd\",\"Ste C\",\"Inglewood, CA 90301\"",
  "item_id": "front-page-jamaican-grille-inglewood",
  "city": "Inglewood",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/SBOhbqJN-pHPtHb6xP7JiQ/o.jpg",
  "latitude": 33.96044,
  "rating": 4.5,
  "review_count": 425,
  "url": "https://www.yelp.com/biz/front-page-jamaican-grille-inglewood?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90301",
  "phone": "+13102169521",
  "price": 2,
  "name": "Front Page Jamaican Grille",
  "state": "CA",
  "categories": ["Caribbean"],
  "longitude": -118.37579
},
{
  "address": "\"8611 Truxton Ave\",\"Los Angeles, CA 90045\"",
  "item_id": "truxtons-american-bistro-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/Cg_0MOUCcXGlt26ax20fYQ/o.jpg",
  "latitude": 33.959442,
  "rating": 4,
  "review_count": 1059,
  "url": "https://www.yelp.com/biz/truxtons-american-bistro-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13104178789",
  "price": 2,
  "name": "Truxton's American Bistro",
  "state": "CA",
  "categories": ["American (New)"],
  "longitude": -118.393598
},
{
  "address": "\"Airport Blvd & Arbor Vitae St\",\"Westchester, CA 90045\"",
  "item_id": "mariscos-el-sabroso-westchester",
  "city": "Westchester",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/Bvjw8ixtQzwC6-3IZ785lw/o.jpg",
  "latitude": 33.9528170404488,
  "rating": 4.5,
  "review_count": 47,
  "url": "https://www.yelp.com/biz/mariscos-el-sabroso-westchester?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "",
  "price": 1,
  "name": "Mariscos El Sabroso",
  "state": "CA",
  "categories": [
    "Food Stands",
    "Food Trucks"
  ],
  "longitude": -118.382548436249
},
{
  "address": "\"8800 S Sepulveda Blvd\",\"Ste 3\",\"Los Angeles, CA 90045\"",
  "item_id": "mono-poke-los-angeles-3",
  "city": "Los Angeles",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/6FmYCXyMoQPZ_qceZivbdQ/o.jpg",
  "latitude": 33.9569892,
  "rating": 4,
  "review_count": 185,
  "url": "https://www.yelp.com/biz/mono-poke-los-angeles-3?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13103388703",
  "price": 1,
  "name": "Mono Poke",
  "state": "CA",
  "categories": [
    "Hawaiian",
    "Salad",
    "Poke"
  ],
  "longitude": -118.3957129
},
{
  "address": "\"8751 La Tijera Blvd\",\"Los Angeles, CA 90045\"",
  "item_id": "the-coffee-co-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/bNhhNDxh_R-IorN1Px_PXw/o.jpg",
  "latitude": 33.957594,
  "rating": 4,
  "review_count": 974,
  "url": "https://www.yelp.com/biz/the-coffee-co-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13106457315",
  "price": 2,
  "name": "The Coffee Co",
  "state": "CA",
  "categories": [
    "American (New)",
    "Breakfast & Brunch",
    "Coffee & Tea"
  ],
  "longitude": -118.394536
},
{
  "address": "\"8806 S Sepulveda Blvd\",\"Los Angeles, CA 90045\"",
  "item_id": "laroccos-pizzeria-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/ySsCtnjOHRpRGH2bD6O7bA/o.jpg",
  "latitude": 33.95682,
  "rating": 4,
  "review_count": 155,
  "url": "https://www.yelp.com/biz/laroccos-pizzeria-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13106420029",
  "price": 1,
  "name": "LaRocco's Pizzeria",
  "state": "CA",
  "categories": [
    "Pizza",
    "Italian"
  ],
  "longitude": -118.39575
},
{
  "address": "\"12121 Bluff Creek Dr\",\"Los Angeles, CA 90094\"",
  "item_id": "hash-los-angeles-2",
  "city": "Los Angeles",
  "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/Dm6Bs2Dl88AvztjO7CDzYQ/o.jpg",
  "latitude": 33.9788656087792,
  "rating": 4.5,
  "review_count": 134,
  "url": "https://www.yelp.com/biz/hash-los-angeles-2?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90094",
  "phone": "+13102828501",
  "price": 1,
  "name": "Hash",
  "state": "CA",
  "categories": [
    "Breakfast & Brunch",
    "Cafes"
  ],
  "longitude": -118.40555605953
},
{
  "address": "\"8736 S Sepulveda Blvd\",\"Ste C\",\"Los Angeles, CA 90045\"",
  "item_id": "kanpai-japanese-sushi-bar-and-grill-2-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/H-sA1gKD4GYcJHW6RbZcYA/o.jpg",
  "latitude": 33.957713033813,
  "rating": 4,
  "review_count": 382,
  "url": "https://www.yelp.com/biz/kanpai-japanese-sushi-bar-and-grill-2-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13106700533",
  "price": 2,
  "name": "Kanpai Japanese Sushi Bar & Grill 2",
  "state": "CA",
  "categories": [
    "Ramen",
    "Sushi Bars"
  ],
  "longitude": -118.395974141022
},
{
  "address": "\"Http//wwwlatteonlocationcom\",\"Los Angeles, CA 90045\"",
  "item_id": "lattes-on-location-los-angeles-5",
  "city": "Los Angeles",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/m04d6EVhQz8U03XJFDGD5g/o.jpg",
  "latitude": 33.9700012207031,
  "rating": 5,
  "review_count": 18,
  "url": "https://www.yelp.com/biz/lattes-on-location-los-angeles-5?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13107567420",
  "price": 0,
  "name": "Lattes On Location",
  "state": "CA",
  "categories": [
    "Caterers",
    "Coffee & Tea"
  ],
  "longitude": -118.376281738281
},
{
  "address": "\"7929 Emerson Ave\",\"Los Angeles, CA 90045\"",
  "item_id": "the-good-pizza-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/Vw-bcdmWfPBzcNu5TL2pWQ/o.jpg",
  "latitude": 33.9691941,
  "rating": 4,
  "review_count": 357,
  "url": "https://www.yelp.com/biz/the-good-pizza-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13102151883",
  "price": 2,
  "name": "The Good Pizza",
  "state": "CA",
  "categories": [
    "Pizza",
    "Italian"
  ],
  "longitude": -118.4062923
},
{
  "address": "\"6224 W Manchester Ave\",\"Los Angeles, CA 90045\"",
  "item_id": "café-solar-los-angeles-2",
  "city": "Los Angeles",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/FEGIA-1rLLJLXSSIAxoCjA/o.jpg",
  "latitude": 33.9595,
  "rating": 4,
  "review_count": 166,
  "url": "https://www.yelp.com/biz/caf%C3%A9-solar-los-angeles-2?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+14242276486",
  "price": 2,
  "name": "Café Solar",
  "state": "CA",
  "categories": [
    "American (New)",
    "Breakfast & Brunch",
    "Coffee & Tea"
  ],
  "longitude": -118.39456
},
{
  "address": "\"6000 W Manchester Ave\",\"Los Angeles, CA 90045\"",
  "item_id": "mariscos-el-guero-taco-truck-and-seafood-los-angeles-6",
  "city": "Los Angeles",
  "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/6raTyBRPm7edbKjqmXEa_w/o.jpg",
  "latitude": 33.9596651,
  "rating": 4.5,
  "review_count": 32,
  "url": "https://www.yelp.com/biz/mariscos-el-guero-taco-truck-and-seafood-los-angeles-6?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13233334740",
  "price": 1,
  "name": "Mariscos El Guero Taco Truck & Seafood",
  "state": "CA",
  "categories": [
    "Mexican",
    "Food Trucks",
    "Seafood"
  ],
  "longitude": -118.388929
},
{
  "address": "\"9132 S Sepulveda Blvd\",\"Los Angeles, CA 90045\"",
  "item_id": "melody-bar-and-grill-los-angeles-2",
  "city": "Los Angeles",
  "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/gl_JedkviH7oKKPT0CsmaA/o.jpg",
  "latitude": 33.95381,
  "rating": 4,
  "review_count": 459,
  "url": "https://www.yelp.com/biz/melody-bar-and-grill-los-angeles-2?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13106701994",
  "price": 2,
  "name": "Melody Bar and Grill",
  "state": "CA",
  "categories": [
    "American (New)",
    "Pizza",
    "Bars"
  ],
  "longitude": -118.39565
},
{
  "address": "\"8632 S Sepulveda Blvd\",\"Ste 101\",\"Los Angeles, CA 90045\"",
  "item_id": "ms-glens-therapeutic-manicures-and-pedicures-los-angeles-2",
  "city": "Los Angeles",
  "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/k_9v6rXUpLbtjtzg2ucABA/o.jpg",
  "latitude": 33.958845,
  "rating": 5,
  "review_count": 317,
  "url": "https://www.yelp.com/biz/ms-glens-therapeutic-manicures-and-pedicures-los-angeles-2?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13106459791",
  "price": 2,
  "name": "Ms Glen's Therapeutic Manicures & Pedicures",
  "state": "CA",
  "categories": [
    "Nail Salons",
    "Massage"
  ],
  "longitude": -118.396035
},
{
  "address": "\"5593 W Manchester Ave\",\"Los Angeles, CA 90045\"",
  "item_id": "dubzzsterz-cigar-lounge-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/d4K4JMO3JBHU0nPXBYY46A/o.jpg",
  "latitude": 33.9600249,
  "rating": 4.5,
  "review_count": 22,
  "url": "https://www.yelp.com/biz/dubzzsterz-cigar-lounge-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+14247025841",
  "price": 2,
  "name": "Dubzzsterz Cigar Lounge",
  "state": "CA",
  "categories": [
    "Tobacco Shops",
    "Lounges"
  ],
  "longitude": -118.3785699
},
{
  "address": "\"8732 S Sepulveda Blvd\",\"Los Angeles, CA 90045\"",
  "item_id": "the-original-brooklyn-water-bagels-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/eOQRQ_F10NFJ9zop-nMc9A/o.jpg",
  "latitude": 33.9578874684391,
  "rating": 3.5,
  "review_count": 468,
  "url": "https://www.yelp.com/biz/the-original-brooklyn-water-bagels-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13106452243",
  "price": 1,
  "name": "The Original Brooklyn Water Bagels",
  "state": "CA",
  "categories": [
    "Bagels",
    "Breakfast & Brunch",
    "Sandwiches"
  ],
  "longitude": -118.396043486133
},
{
  "address": "\"12604 Bluff Creek Dr\",\"Playa Vista, CA 90094\"",
  "item_id": "playa-vista-dog-park-playa-vista",
  "city": "Playa Vista",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/7g73OyJgct7Jos8EG1vmWw/o.jpg",
  "latitude": 33.9757481,
  "rating": 4.5,
  "review_count": 56,
  "url": "https://www.yelp.com/biz/playa-vista-dog-park-playa-vista?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90094",
  "phone": "+12135873798",
  "price": 0,
  "name": "Playa Vista Dog Park",
  "state": "CA",
  "categories": ["Dog Parks"],
  "longitude": -118.4115463
},
{
  "address": "\"5844 W Manchester Ave\",\"Los Angeles, CA 90045\"",
  "item_id": "jinos-pars-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/js_s7N0Vr4tOWMRCAWPdwg/o.jpg",
  "latitude": 33.9596851,
  "rating": 4,
  "review_count": 386,
  "url": "https://www.yelp.com/biz/jinos-pars-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13106456666",
  "price": 2,
  "name": "Jino's Pars",
  "state": "CA",
  "categories": ["Persian/Iranian"],
  "longitude": -118.3843376
},
{
  "address": "\"6233 W 87th St\",\"Los Angeles, CA 90045\"",
  "item_id": "jags-barber-shop-los-angeles-2",
  "city": "Los Angeles",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/K8bNOofSHqRS_0Yw9WTKUA/o.jpg",
  "latitude": 33.958752,
  "rating": 5,
  "review_count": 309,
  "url": "https://www.yelp.com/biz/jags-barber-shop-los-angeles-2?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13103371617",
  "price": 1,
  "name": "Jag's Barber Shop",
  "state": "CA",
  "categories": ["Barbers"],
  "longitude": -118.394211
},
{
  "address": "\"8321 Lincoln Blvd\",\"Los Angeles, CA 90045\"",
  "item_id": "humble-potato-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/_-6vicCnXY4HXeisrYr86Q/o.jpg",
  "latitude": 33.9620098,
  "rating": 4,
  "review_count": 756,
  "url": "https://www.yelp.com/biz/humble-potato-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13239892242",
  "price": 2,
  "name": "Humble Potato",
  "state": "CA",
  "categories": [
    "American (New)",
    "Burgers",
    "Sandwiches"
  ],
  "longitude": -118.4214944
},
{
  "address": "\"12150 Millennium Dr\",\"Ste 101\",\"Los Angeles, CA 90094\"",
  "item_id": "tocaya-organica-playa-vista-los-angeles-4",
  "city": "Los Angeles",
  "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/m12zVhkIhMERRI8U50T8GA/o.jpg",
  "latitude": 33.979614868581,
  "rating": 4.5,
  "review_count": 99,
  "url": "https://www.yelp.com/biz/tocaya-organica-playa-vista-los-angeles-4?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90094",
  "phone": "+14242896105",
  "price": 2,
  "name": "Tocaya Organica - Playa Vista",
  "state": "CA",
  "categories": [
    "Mexican",
    "Vegetarian",
    "Vegan"
  ],
  "longitude": -118.408223949385
},
{
  "address": "\"8540 S Sepulveda Blvd\",\"Ste 106\",\"Los Angeles, CA 90045\"",
  "item_id": "joshua-m-kaye-dpm-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/9-eou92SUjw-dOjigd0VUg/o.jpg",
  "latitude": 33.9601974487305,
  "rating": 5,
  "review_count": 67,
  "url": "https://www.yelp.com/biz/joshua-m-kaye-dpm-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13106413555",
  "price": 0,
  "name": "Joshua M Kaye, DPM",
  "state": "CA",
  "categories": ["Podiatrists"],
  "longitude": -118.395713806152
},
{
  "address": "\"1 World Way\",\"Los Angeles, CA 90045\"",
  "item_id": "sealegs-wine-bar-los-angeles-2",
  "city": "Los Angeles",
  "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/3yskY3avUc7MQorj7zwx5w/o.jpg",
  "latitude": 33.9443749,
  "rating": 4,
  "review_count": 35,
  "url": "https://www.yelp.com/biz/sealegs-wine-bar-los-angeles-2?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+14242278295",
  "price": 2,
  "name": "SeaLegs Wine Bar",
  "state": "CA",
  "categories": [
    "American (New)",
    "Wine Bars",
    "Breakfast & Brunch"
  ],
  "longitude": -118.3984405
},
{
  "address": "\"613 W Manchester Blvd\",\"Inglewood, CA 90301\"",
  "item_id": "marias-ricos-tacos-inglewood-3",
  "city": "Inglewood",
  "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/CJrDuNedrnhnKwL5jyUi5Q/o.jpg",
  "latitude": 33.96199,
  "rating": 4.5,
  "review_count": 485,
  "url": "https://www.yelp.com/biz/marias-ricos-tacos-inglewood-3?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90301",
  "phone": "+13106728226",
  "price": 1,
  "name": "Maria's Ricos Tacos",
  "state": "CA",
  "categories": [
    "Breakfast & Brunch",
    "Tacos",
    "Sandwiches"
  ],
  "longitude": -118.36702
},
{
  "address": "\"8622 S Sepulveda Blvd\",\"Los Angeles, CA 90045\"",
  "item_id": "blue-diamond-jeweler-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/udxdvOc6BecmSAUj0SmLDg/o.jpg",
  "latitude": 33.9591774344444,
  "rating": 5,
  "review_count": 75,
  "url": "https://www.yelp.com/biz/blue-diamond-jeweler-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13104173090",
  "price": 2,
  "name": "Blue Diamond Jeweler",
  "state": "CA",
  "categories": [
    "Jewelry",
    "Watch Repair",
    "Jewelry Repair"
  ],
  "longitude": -118.396175354719
},
{
  "address": "\"5622 W Manchester Ave\",\"Los Angeles, CA 90045\"",
  "item_id": "lei-aloha-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/S3MGPKqEUvrZFhbavMdd5w/o.jpg",
  "latitude": 33.9598453044891,
  "rating": 4.5,
  "review_count": 35,
  "url": "https://www.yelp.com/biz/lei-aloha-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13106414544",
  "price": 1,
  "name": "Lei Aloha",
  "state": "CA",
  "categories": [
    "Sports Bars",
    "Lounges"
  ],
  "longitude": -118.379235863686
},
{
  "address": "\"8620 S Sepulveda Blvd\",\"Westchester, CA 90045\"",
  "item_id": "el-tarasco-westchester",
  "city": "Westchester",
  "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/Pnn1cNquv0sbUYVWMbOxVw/o.jpg",
  "latitude": 33.9591064453125,
  "rating": 3.5,
  "review_count": 294,
  "url": "https://www.yelp.com/biz/el-tarasco-westchester?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13103380399",
  "price": 1,
  "name": "El Tarasco",
  "state": "CA",
  "categories": ["Mexican"],
  "longitude": -118.39575958252
},
{
  "address": "\"1 World Way\",\"Tom Bradley International Terminal\",\"Los Angeles, CA 90045\"",
  "item_id": "qantas-first-class-lounge-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/tYvLP7KycsffmHuar82AyA/o.jpg",
  "latitude": 33.9430448701412,
  "rating": 4.5,
  "review_count": 34,
  "url": "https://www.yelp.com/biz/qantas-first-class-lounge-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13103480750",
  "price": 1,
  "name": "Qantas First Class Lounge",
  "state": "CA",
  "categories": ["Airport Lounges"],
  "longitude": -118.409567323246
},
{
  "address": "\"6218 B Manchester Ave\",\"Los Angeles, CA 90045\"",
  "item_id": "sassy-ladies-beauty-bar-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/oDcdMspa7R_UotL_ugXHHw/o.jpg",
  "latitude": 33.9595,
  "rating": 4.5,
  "review_count": 269,
  "url": "https://www.yelp.com/biz/sassy-ladies-beauty-bar-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+14242279505",
  "price": 2,
  "name": "Sassy Ladies Beauty Bar",
  "state": "CA",
  "categories": [
    "Waxing",
    "Day Spas",
    "Skin Care"
  ],
  "longitude": -118.39423
},
{
  "address": "\"9146 S Sepulveda Blvd\",\"Los Angeles, CA 90045\"",
  "item_id": "melody-pizza-los-angeles-3",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/9-5sZfTQnRq8lMSoXm-Puw/o.jpg",
  "latitude": 33.9533930010657,
  "rating": 4,
  "review_count": 246,
  "url": "https://www.yelp.com/biz/melody-pizza-los-angeles-3?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+14242277686",
  "price": 2,
  "name": "Melody Pizza",
  "state": "CA",
  "categories": ["Pizza"],
  "longitude": -118.39601442576
},
{
  "address": "\"8740 S Sepulveda Blvd\",\"Ste 140\",\"Westchester, CA 90045\"",
  "item_id": "ayara-lūk-westchester-5",
  "city": "Westchester",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/naVyGrS6G0Foq16KOvKohA/o.jpg",
  "latitude": 33.9576592,
  "rating": 4,
  "review_count": 96,
  "url": "https://www.yelp.com/biz/ayara-l%C5%ABk-westchester-5?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13108814498",
  "price": 2,
  "name": "Ayara LŪK",
  "state": "CA",
  "categories": [
    "Soup",
    "Thai",
    "Noodles"
  ],
  "longitude": -118.3957758
},
{
  "address": "\"8320 Lincoln Blvd\",\"Los Angeles, CA 90045\"",
  "item_id": "kcs-crepes-cafe-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/J4a-UE9hITpPgm5bntYglg/o.jpg",
  "latitude": 33.962223,
  "rating": 4,
  "review_count": 668,
  "url": "https://www.yelp.com/biz/kcs-crepes-cafe-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13103489697",
  "price": 1,
  "name": "KC's Crepes Cafe",
  "state": "CA",
  "categories": [
    "Creperies",
    "Coffee & Tea"
  ],
  "longitude": -118.420906
},
{
  "address": "\"6833 Park Ter\",\"Los Angeles, CA 90045\"",
  "item_id": "pure-energy-cafe-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/jc-ZA5XtAVW5T-xRXKILUQ/o.jpg",
  "latitude": 33.976406,
  "rating": 4,
  "review_count": 85,
  "url": "https://www.yelp.com/biz/pure-energy-cafe-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13102166730",
  "price": 2,
  "name": "Pure Energy Cafe",
  "state": "CA",
  "categories": ["Sandwiches"],
  "longitude": -118.393363
},
{
  "address": "\"6218 W Manchester Ave\",\"Los Angeles, CA 90045\"",
  "item_id": "yoga-bliss-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/PVQ-z4NZxKczEw_9z-sFzA/o.jpg",
  "latitude": 33.9595108032227,
  "rating": 5,
  "review_count": 37,
  "url": "https://www.yelp.com/biz/yoga-bliss-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+14244420647",
  "price": 0,
  "name": "Yoga Bliss",
  "state": "CA",
  "categories": ["Yoga"],
  "longitude": -118.394241333008
},
{
  "address": "\"1 World Way\",\"Fl 5\",\"Tom Bradley International Terminal\",\"Los Angeles, CA 90045\"",
  "item_id": "star-alliance-lounge-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/bphywNyu25nx1DvaGEG4yQ/o.jpg",
  "latitude": 33.9438975942788,
  "rating": 4,
  "review_count": 93,
  "url": "https://www.yelp.com/biz/star-alliance-lounge-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "",
  "price": 1,
  "name": "Star Alliance Lounge",
  "state": "CA",
  "categories": ["Airport Lounges"],
  "longitude": -118.41024125872
},
{
  "address": "\"8325 Lincoln Blvd\",\"Los Angeles, CA 90045\"",
  "item_id": "kanpai-japanese-sushi-bar-and-grill-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/H83h0rIlTu5-vReV1CXMAg/o.jpg",
  "latitude": 33.96185,
  "rating": 4,
  "review_count": 1211,
  "url": "https://www.yelp.com/biz/kanpai-japanese-sushi-bar-and-grill-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13103387223",
  "price": 3,
  "name": "Kanpai Japanese Sushi Bar & Grill",
  "state": "CA",
  "categories": [
    "Sushi Bars",
    "Japanese",
    "Bars"
  ],
  "longitude": -118.4214
},
{
  "address": "\"6212 W Manchester Ave\",\"Los Angeles, CA 90045\"",
  "item_id": "pacos-tacos-los-angeles-4",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/rkdcSaFmadOdaLKFNV38IQ/o.jpg",
  "latitude": 33.9595108032227,
  "rating": 3.5,
  "review_count": 573,
  "url": "https://www.yelp.com/biz/pacos-tacos-los-angeles-4?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13106458692",
  "price": 2,
  "name": "Paco's Tacos",
  "state": "CA",
  "categories": ["Mexican"],
  "longitude": -118.394073486328
},
{
  "address": "\"6171 W Century Blvd\",\"Los Angeles, CA 90045\"",
  "item_id": "the-original-rinaldis-deli-and-cafe-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/XqhvYA_dJ-9l2nUiBr2Z2g/o.jpg",
  "latitude": 33.945707390704,
  "rating": 4.5,
  "review_count": 26,
  "url": "https://www.yelp.com/biz/the-original-rinaldis-deli-and-cafe-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+14243518799",
  "price": 2,
  "name": "The Original Rinaldi's Deli and Cafe",
  "state": "CA",
  "categories": [
    "Delis",
    "Cafes",
    "Sandwiches"
  ],
  "longitude": -118.393373557043
},
{
  "address": "\"1041 W Manchester Blvd\",\"Inglewood, CA 90301\"",
  "item_id": "tumbys-pizza-inglewood",
  "city": "Inglewood",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/26RUiv_lFXysCOeyl5P9jg/o.jpg",
  "latitude": 33.9600850707484,
  "rating": 4,
  "review_count": 331,
  "url": "https://www.yelp.com/biz/tumbys-pizza-inglewood?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90301",
  "phone": "+13106411203",
  "price": 1,
  "name": "Tumby's Pizza",
  "state": "CA",
  "categories": [
    "Pizza",
    "Italian",
    "Chicken Wings"
  ],
  "longitude": -118.375004384668
},
{
  "address": "\"6208 Manchester Ave\",\"Los Angeles, CA 90045\"",
  "item_id": "la-vista-cleaners-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/zTtGTdLA-JhzZL33ETOCdg/o.jpg",
  "latitude": 33.9595947265625,
  "rating": 4.5,
  "review_count": 257,
  "url": "https://www.yelp.com/biz/la-vista-cleaners-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13106700175",
  "price": 1,
  "name": "LA Vista Cleaners",
  "state": "CA",
  "categories": [
    "Laundry Services",
    "Sewing & Alterations"
  ],
  "longitude": -118.393913269043
},
{
  "address": "\"8740 S Sepulveda Blvd\",\"Ste 160\",\"Los Angeles, CA 90045\"",
  "item_id": "new-care-clinic-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/TFia0XJ3oNLw0gR3836WhQ/o.jpg",
  "latitude": 33.9576169,
  "rating": 5,
  "review_count": 102,
  "url": "https://www.yelp.com/biz/new-care-clinic-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13106452273",
  "price": 0,
  "name": "New Care Clinic",
  "state": "CA",
  "categories": ["Urgent Care"],
  "longitude": -118.3958341
},
{
  "address": "\"8320 Lincoln Blvd\",\"Los Angeles, CA 90045\"",
  "item_id": "taj-india-palace-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/cXHeBt2f-_Rwo-tzNpWimw/o.jpg",
  "latitude": 33.962156,
  "rating": 4,
  "review_count": 370,
  "url": "https://www.yelp.com/biz/taj-india-palace-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13103371423",
  "price": 2,
  "name": "Taj India Palace",
  "state": "CA",
  "categories": ["Indian"],
  "longitude": -118.421053
},
{
  "address": "\"Los Angeles, CA 90045\"",
  "item_id": "the-locksmith-guys-los-angeles",
  "city": "Los Angeles",
  "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/u0Qjjx7jT1xWbiBn5j2AIA/o.jpg",
  "latitude": 33.9700012207031,
  "rating": 5,
  "review_count": 134,
  "url": "https://www.yelp.com/biz/the-locksmith-guys-los-angeles?adjust_creative=ocDAWV6tkSxVGkKwE2dErw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ocDAWV6tkSxVGkKwE2dErw",
  "zipcode": "90045",
  "phone": "+13107777878",
  "price": 0,
  "name": "The Locksmith Guys",
  "state": "CA",
  "categories": ["Keys & Locksmiths"],
  "longitude": -118.376281738281
},
]